<!DOCTYPE html>
<html ng-app="app">
    <head>
        <meta charset="utf-8"/>
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <title>Admin</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="./../assets/node_modules/bootstrap/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="./../assets/node_modules/font-awesome/css/font-awesome.min.css">
        <link rel="stylesheet" href="./../assets/node_modules/angular-loading-bar/build/loading-bar.min.css">
        <link rel="stylesheet" href="./../assets/node_modules/icheck/skins/square/blue.css">
        <link rel="stylesheet" href="./../assets/lib/adminLTE/AdminLTE.min.css">
        <link rel="stylesheet" href="./../assets/lib/adminLTE/skin-blue.min.css">
        <link rel="stylesheet" href="./../assets/css/admin/style.min.css">
    </head>

    <body class="hold-transition skin-blue fixed sidebar-mini">
        <div ui-view="content" class="ui-content"></div>
    </body>

    <script src="./../assets/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="./../assets/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="./../assets/lib/adminLTE/app.min.js"></script>
    <script src="./../assets/node_modules/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <script src="./../assets/node_modules/icheck/icheck.min.js"></script>

    <script src="./../assets/node_modules/angular/angular.min.js"></script>
    <script src="./../assets/node_modules/angular-ui-router/release/angular-ui-router.min.js"></script>
    <script src="./../assets/node_modules/angular-resource/angular-resource.min.js"></script>
    <script src="./../assets/node_modules/angular-animate/angular-animate.min.js"></script>
    <script src="./../assets/node_modules/angular-loading-bar/build/loading-bar.min.js"></script>

    <script src="./../assets/js/admin/main.js"></script>
    <script src="./../assets/js/admin/controllers/controllers.js"></script>
    <script src="./../assets/js/admin/services/services.js"></script>
</html>
